# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "https://gitlab.shortcord.com/shortcord/catstodon.git";
    rev = "071a368a7166b9d53567af6ddda1b1fc010f1d20";
    sha256 = "0hhqzc80gc723jjzw5ah1bjg26ra8fl2nli3z1fk64s7ccdsb3xg";
  };
in applyPatches {
  inherit src;
  patches = [];
}
