stages:
  - build

build:
  image:
    name: nixos/nix:latest
  stage: build
  before_script:
    - eval $(ssh-agent -s)
    - chmod 400 "${SSH_PRIVATE_KEY}"
    - ssh-add "${SSH_PRIVATE_KEY}"
    - mkdir -p ~/.ssh/ && chmod 0700 ~/.ssh/
    - mkdir -p ~/.config/nix/
    - echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf
    - nix-channel --remove nixpkgs
    - nix-channel --add https://nixos.org/channels/nixos-23.05 nixpkgs
    - nix-channel --update
  script:
    - nix develop --command -- colmena build
  # rules:
  #   - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'