# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "https://github.com/CatCatNya/catstodon.git";
    rev = "037fcd9d31c411692c67444efd5a1de284ade5d6";
    sha256 = "1wh71k6q28ra3vays1vblby8xi0cqyr4dmy38jrjwgxzkr97g4w6";
  };
in applyPatches {
  inherit src;
  patches = [];
}
