# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches, patches ? [] }:
let
  version = "37fcd9d31c411692c67444efd5a1de284ade5d6";
in
(
  applyPatches {
    src = fetchgit {
      url = "https://github.com/CatCatNya/catstodon.git";
      rev = "${version}";
      hash = "sha256-hpN3Up6/Py6zRMPXRrLHDMSO/KJrB+3VHiojgc0MB/I=";
    };
    patches = patches ++ [];
  }) // {
  inherit version;
  yarnHash = "sha256-8fUJ1RBQZ16R3IpA/JEcn+PO04ApQ9TkHuYKycvV8BY=";
}
